name: deploy

on:
  workflow_call:
    inputs:
      environment:
        description: Environment
        required: true
        type: string
jobs:
  pass-thgrough:
    name: pass-thgrough
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: |
        echo 'Variables'
        env | sort
