name: deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        type: string
        options:
          - dev
          - uat
          - prod
  workflow_call:
    inputs:
      environment:
        description: Environment
        required: true
        type: string

jobs:
  pass-thgrough:
    name: pass-thgrough
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ShowVars
        run: |
          set -ex
          echo 'Environment : ${{ inputs.environment }}'
          echo 'Variables'
          env | sort
          echo 'Env Specific Variables'
          echo '${{ vars.MYVAR_VALUE1 }}'

