name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        description: Environment
        required: true
        type: string
      git_tag:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        type: choice
        options:
          - dev
          - uat
          - prod

jobs:
  pass-thgrough:
    name: pass-thgrough
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.git_tag }}

      - name: ShowVars
        run: |
          set -ex
          echo 'Running on Tag : >${{ inputs.git_tag }}<'
          echo 'Environment : ${{ inputs.environment }}'
          echo 'Env Specific Variables'
          echo '${{ vars.MYVAR_VALUE1 }}'
          echo 'Env Specific Secrets'
          echo '${{ secrets.MYVAR_SECRET1 }}'

